### ISSUE TITLE
Bare equations with align

### ISSUE THREAD

**Issue by tmthyln** [tlienart/Xranklin.jl#86] opened 2022-02-10 03:34 UTC
I'm currently working on converting a (somewhat old) website that I have in Franklin.jl over.

I believe (and maybe I'm wrong), but latex equations using the `align` environment used to be supported in Franklin in pure markdown (not sure if this was special-cased into the Franklin parser). Something like:

```md
\begin{align}
    \mu_{1/2}\big[ T(n) \big] &= n(n+1) + 2 \sum_{i=2}^n \dfrac{-i}{\lg\big( 1-\frac{1}{i} \big)} \\
    &< n(n+1) + 2 \sum_{i=2}^n i^2 \\
    &= n(n+1) + \dfrac{n(n+1)(2n+1)}{3} \reason{(sum of squares)} \\
    &\in O(n^3)
\end{align}
```
in pure markdown.

But now, I get the error

```
ERROR: FranklinParser.FranklinParserException(:BlockNotClosed, "An opening \\begin{align} was found but either not followed by a brace or\nleft open.\n")
Stacktrace:
  [1] parser_exception
    @ ~/.julia/packages/FranklinParser/up5TR/src/utils/errors.jl:6 [inlined]
  [2] enverr(n::String)
    @ FranklinParser ~/.julia/packages/FranklinParser/up5TR/src/partition.jl:227
  [3] md_grouper(blocks::Vector{FranklinParser.Block})
    @ FranklinParser ~/.julia/packages/FranklinParser/up5TR/src/partition.jl:180
  [4] |>
    @ ./operators.jl:858 [inlined]
  [5] convert_md(md::SubString{String}, c::Xranklin.LocalContext; tohtml::Bool, nop::Bool, kw::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Xranklin ~/.julia/packages/Xranklin/5a7wL/src/convert/markdown/md_core.jl:62
  [6] convert_md(md::SubString{String}, c::Xranklin.LocalContext)
    @ Xranklin ~/.julia/packages/Xranklin/5a7wL/src/convert/markdown/md_core.jl:51
  [7] html(md::SubString{String}, c::Xranklin.LocalContext; kw::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Xranklin ~/.julia/packages/Xranklin/5a7wL/src/convert/markdown/md_core.jl:125
  [8] html
    @ ~/.julia/packages/Xranklin/5a7wL/src/convert/markdown/md_core.jl:125 [inlined]
  [9] #html#96
    @ ~/.julia/packages/Xranklin/5a7wL/src/convert/markdown/md_core.jl:129 [inlined]
 [10] html
    @ ~/.julia/packages/Xranklin/5a7wL/src/convert/markdown/md_core.jl:129 [inlined]
 [11] _process_md_file_html(ctx::Xranklin.LocalContext, page_content_md::String)
    @ Xranklin ~/.julia/packages/Xranklin/5a7wL/src/process/md.jl:359
 [12] process_md_file_io!(io::IOBuffer, gc::Xranklin.GlobalContext{Xranklin.LocalContext}, fpath::String; opath::String, initial_pass::Bool, in_gc::Bool, tohtml::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/5a7wL/src/process/md.jl:294
 [13] process_md_file(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, fpath::String, opath::String; initial_pass::Bool, kw::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Xranklin ~/.julia/packages/Xranklin/5a7wL/src/process/md.jl:59
 [14] process_file(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, fpair::Pair{String, String}, case::Symbol, t::Float64; skip_files::Vector{Pair{String, String}}, initial_pass::Bool, final::Bool, reproc::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/5a7wL/src/process/process.jl:67
 [15] full_pass(gc::Xranklin.GlobalContext{Xranklin.LocalContext}, watched_files::OrderedCollections.LittleDict{Symbol, OrderedCollections.LittleDict{Pair{String, String}, Float64, KS, VS} where {KS<:(Union{var"#s4", var"#s3"} where {var"#s4"<:Tuple, var"#s3"<:(Vector{T} where T)}), VS<:(Union{var"#s4", var"#s3"} where {var"#s4"<:Tuple, var"#s3"<:(Vector{T} where T)})}, Vector{Symbol}, Vector{OrderedCollections.LittleDict{Pair{String, String}, Float64, KS, VS} where {KS<:(Union{var"#s4", var"#s3"} where {var"#s4"<:Tuple, var"#s3"<:(Vector{T} where T)}), VS<:(Union{var"#s4", var"#s3"} where {var"#s4"<:Tuple, var"#s3"<:(Vector{T} where T)})}}}; skip_files::Vector{Pair{String, String}}, layout_changed::Bool, config_changed::Bool, utils_changed::Bool, final::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/5a7wL/src/build/serve.jl:288
 [16] serve(d::String; dir::String, folder::String, clear::Bool, final::Bool, single::Bool, debug::Bool, cleanup::Bool, port::Int64, host::String, launch::Bool)
    @ Xranklin ~/.julia/packages/Xranklin/5a7wL/src/build/serve.jl:100
 [17] top-level scope
    @ REPL[6]:1
```

when I try to serve.

Is this not supported syntax anymore?

**Comment by tmthyln** [comment] 2022-02-10 03:59
Repository is [here](https://github.com/tmthyln/personal-website-xranklin) (although I haven't reconfigured it build on gh yet, plus there are other issues I still need to get a handle on).

**Comment by tlienart** [comment] 2022-02-10 06:31
This should work, thanks for the heads up, ill check what's going on :)

**Comment by tlienart** [comment] 2022-02-10 09:51
Yeah so the problem is not with `align`; I've done some work on a branch in your repo but there's something weird going on that I need to understand and fix with parsing your bogosort post. 

It might take me a while to figure this out but I'll ping you there once that's fixed; thanks for testing things!

**Comment by tlienart** [comment] 2022-02-10 16:21
alright this ended up being a fairly sneaky bug, very glad you provided a nice test case for it. It should be fixed. I've pushed a load of small changes to your repo as well. It's not fully functional yet because you make use of `\fig` which is not yet implemented (not sure I'll bake that one in, maybe we can just add it to your `utils`) there may be a few other glitches here and there but the posts mostly work.

**Closed by tlienart** 2022-02-10 16:21 UTC
